APP_TITLE    := N.O.V.A. 3
APP_AUTHOR   := Gameloft, mark
APP_VERSION  := 1.0.7
TARGET       := nova3
PORT_PAYLOAD := nova3_nx

TOPDIR ?= $(CURDIR)
A32    ?= $(TOPDIR)/../runtime
include $(A32)/launcher/launcher.mk
